backend:
  name: git-gateway
  branch: master
media_folder: static/img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/cms_content.md"
      fields: 
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Subtitle", name: "subtitle", widget: "string" }
        - label: "Navigational Links"
          name: "nav_link"
          widget: list
          fields:
              - { label: "Label", name: "label", widget: "string"}
              - { label: "URL", name: "url", widget: "string"}
        - label: "Logo"
          name: "logo"
          widget: "image"
          default: "/static/bulma-logo.png"
          media_library:
            config:
              multiple: true
        # - { label: "Body", name: "body", widget: "markdown"}
        # - label: 'Cats'
        #   name: "cats"
        #   widget: list
        #   fields: 
        #     - { label: "Name", name: "name", widget: "string"}
        #     - { label: "Description", name: "description", widget: "text"}